use_frameworks!

target 'LQBTestLibrary_Example' do
  pod 'LQBTestLibrary', :path => '../'

  target 'LQBTestLibrary_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
